@startumltitle UML Diagram - UserDTOBuilderclass Client <Director> {}abstract class UserDTOBuilder <<abstract>> {}class UserRestDTOBuilder <<ConcreteBuilder>> extends UserDTOBuilder {}class UserWebDTOBuilder <<ConcreteBuilder>> extends UserDTOBuilder {}abstract class UserDTO <<abstract>> {}class UserRestDTO <<instance>> extends UserDTO {}class UserWebDTO <<instance>> extends UserDTO {}UserRestDTOBuilder *.. UserRestDTOUserWebDTOBuilder *.. UserWebDTOClient ..> UserDTOBuilderUserDTOBuilder *--> UserDTO@enduml